### ISSUE TITLE
Unable to set size of draw target element?

### ISSUE THREAD

**Issue by flandry19** [bijection/g9#1]
Hi,

When I do an 'insertInto' call, the SVG which is created has its viewbox automatically set to some drawing size and offset.  If I am rendering into a fixed size Div tag, how to I ensure that the resulting drawing is not arbitrarily re-scaled?

Thanks,
Forrest

**Comment by bijection** [comment]
You should be able to set it with css, with a rule like `#mydiv > svg {  height: 100%; width: 100% }`.

Does that work for you?

**Comment by flandry19** [comment]
Thanks.  Yes, that worked.

Would be good to add a mention of this somewhere in the example docs, however, since the mod targets something dynamically generated by code, it is not obvious that that is the method by which the required effect is to be obtained.  The more natural assumption of setting the layout size of the element itself, by CSS, does not result in the expected behavior.  Hence,  people who begin by constructing the absolute most simple example from scratch, from raw html, as a test, will definitely see what looks like an initial failed lib verify.

**Comment by bijection** [comment]
Glad it worked! I've added a note to the docs.
