### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kai-qu** [bijection/g9#5]
Hi all, thanks for this awesome library! May I ask what the license is for using it?

**Comment by mootari** [comment]
The license appears to be [MIT](https://github.com/bijection/g9/blob/master/License.md). I'd argue that you can ignore the mention of "ISC" in [package.json](https://github.com/bijection/g9/blob/4912bea2c0907b15dbb912ce8340718263629c95/package.json#L12) as it is the `npm init`default.

**Comment by kai-qu** [comment]
Thanks @mootari!
